// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using PracticoII_Web.Data.Models;

namespace PracticoII_Web.Data.Context;

public partial class Bug_Tracker_BDDContext : DbContext
{
    public Bug_Tracker_BDDContext(DbContextOptions<Bug_Tracker_BDDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Asignacione> Asignaciones { get; set; }

    public virtual DbSet<Comentario> Comentarios { get; set; }

    public virtual DbSet<Incidente> Incidentes { get; set; }

    public virtual DbSet<Proyecto> Proyectos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Asignacione>(entity =>
        {
            entity.HasKey(e => e.IdAsignacion).HasName("PK__Asignaci__A7235DFF7BE6CA77");

            entity.Property(e => e.FechaAsignacion).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.IdUsuarioAsignadoNavigation).WithMany(p => p.Asignaciones)
                .HasForeignKey(d => d.IdUsuarioAsignado)
                .HasConstraintName("FK__Asignacio__IdUsu__47DBAE45");
        });

        modelBuilder.Entity<Comentario>(entity =>
        {
            entity.HasKey(e => e.IdComentario).HasName("PK__Comentar__DDBEFBF9D1704C98");

            entity.Property(e => e.Fecha).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Texto).HasMaxLength(1000);

            entity.HasOne(d => d.IdUsuarioNavigation).WithMany(p => p.Comentarios)
                .HasForeignKey(d => d.IdUsuario)
                .HasConstraintName("FK__Comentari__IdUsu__4316F928");
        });

        modelBuilder.Entity<Incidente>(entity =>
        {
            entity.HasKey(e => e.IdIncidente).HasName("PK__Incident__E92B13DF71970A38");

            entity.Property(e => e.Titulo)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.IdProyectoNavigation).WithMany(p => p.Incidentes)
                .HasForeignKey(d => d.IdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Incidente__IdPro__17036CC0");

            entity.HasOne(d => d.IdUsuarioReportaNavigation).WithMany(p => p.Incidentes)
                .HasForeignKey(d => d.IdUsuarioReporta)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Incidente__IdUsu__160F4887");
        });

        modelBuilder.Entity<Proyecto>(entity =>
        {
            entity.HasKey(e => e.IdProyecto).HasName("PK__Proyecto__F48886730F7798F1");

            entity.Property(e => e.IdProyecto).ValueGeneratedOnAdd();
            entity.Property(e => e.Descripcion).HasMaxLength(500);
            entity.Property(e => e.Nombre).HasMaxLength(100);

            entity.HasOne(d => d.IdProyectoNavigation).WithOne(p => p.Proyecto)
                .HasForeignKey<Proyecto>(d => d.IdProyecto)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Proyectos_Asignaciones");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.IdUsuario).HasName("PK__Usuarios__5B65BF97431520ED");

            entity.HasIndex(e => e.Email, "UQ__Usuarios__A9D105344A844440").IsUnique();

            entity.Property(e => e.Contraseña)
                .HasMaxLength(25)
                .IsFixedLength();
            entity.Property(e => e.Email).HasMaxLength(100);
            entity.Property(e => e.Nombre).HasMaxLength(100);
            entity.Property(e => e.Rol).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}