// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticoII_Web.Data.Models;

public partial class Asignacione
{
    public int IdAsignacion { get; set; }

    public int? IdUsuarioAsignado { get; set; }

    public DateOnly? FechaAsignacion { get; set; }

    public virtual Usuario IdUsuarioAsignadoNavigation { get; set; }

    public virtual Proyecto Proyecto { get; set; }
}