// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticoII_Web.Data.Models;

public partial class Comentario
{
    public int IdComentario { get; set; }

    public int? IdUsuario { get; set; }

    public string Texto { get; set; }

    public DateOnly? Fecha { get; set; }

    public virtual Usuario IdUsuarioNavigation { get; set; }
}