// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticoII_Web.Data.Models;

public partial class Incidente
{
    public int IdIncidente { get; set; }

    public string Titulo { get; set; }

    public string Descripcion { get; set; }

    public int IdUsuarioReporta { get; set; }

    public int IdProyecto { get; set; }

    public virtual Proyecto IdProyectoNavigation { get; set; }

    public virtual Usuario IdUsuarioReportaNavigation { get; set; }
}