// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticoII_Web.Data.Models;

public partial class Proyecto
{
    public int IdProyecto { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public DateOnly? FechaInicio { get; set; }

    public DateOnly? FechaFin { get; set; }

    public int? IdAsignacion { get; set; }

    public virtual Asignacione IdProyectoNavigation { get; set; }

    public virtual ICollection<Incidente> Incidentes { get; set; } = new List<Incidente>();
}